// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmegaFY.Blog.Data.EF.Context;

namespace OmegaFY.Blog.Data.EF.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210113181651_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Comentarios.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostagemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Comentarios.Reacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComentarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ReacaoUsuario")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SubComentarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("SubComentarioId");

                    b.ToTable("Reacoes");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Comentarios.SubComentario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComentarioId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostagemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId1");

                    b.ToTable("SubComentarios");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Postagens.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Estrelas")
                        .HasColumnType("tinyint");

                    b.Property<float>("Nota")
                        .HasColumnType("real");

                    b.Property<Guid>("PostagemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Postagens.Compartilhamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCompartilhamento")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PostagemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.ToTable("Compartilhamentos");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Postagens.Postagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Oculta")
                        .HasColumnType("bit");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_PostagemId")
                        .IsClustered();

                    b.ToTable("Postagens");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Comentarios.Comentario", b =>
                {
                    b.HasOne("OmegaFY.Blog.Domain.Entities.Postagens.Postagem", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemId")
                        .HasConstraintName("FK_ComentarioPostagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Shared.Corpo", "Corpo", b1 =>
                        {
                            b1.Property<Guid>("ComentarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Conteudo")
                                .IsRequired()
                                .HasColumnType("varchar(1000)")
                                .HasColumnName("Corpo");

                            b1.HasKey("ComentarioId");

                            b1.ToTable("Comentarios");

                            b1.WithOwner()
                                .HasForeignKey("ComentarioId");
                        });

                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Shared.DetalhesModificacao", "DetalhesModificacao", b1 =>
                        {
                            b1.Property<Guid>("ComentarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DataCriacao")
                                .HasColumnType("datetime")
                                .HasColumnName("DataCriacao");

                            b1.Property<DateTime?>("DataModificacao")
                                .HasColumnType("datetime")
                                .HasColumnName("DataModificacao");

                            b1.HasKey("ComentarioId");

                            b1.ToTable("Comentarios");

                            b1.WithOwner()
                                .HasForeignKey("ComentarioId");
                        });

                    b.Navigation("Corpo");

                    b.Navigation("DetalhesModificacao");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Comentarios.Reacao", b =>
                {
                    b.HasOne("OmegaFY.Blog.Domain.Entities.Comentarios.Comentario", null)
                        .WithMany("Reacoes")
                        .HasForeignKey("ComentarioId")
                        .HasConstraintName("FK_ReacaoComentarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmegaFY.Blog.Domain.Entities.Comentarios.SubComentario", null)
                        .WithMany("Reacoes")
                        .HasForeignKey("SubComentarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Comentarios.SubComentario", b =>
                {
                    b.HasOne("OmegaFY.Blog.Domain.Entities.Comentarios.Comentario", null)
                        .WithMany("SubComentarios")
                        .HasForeignKey("ComentarioId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Shared.Corpo", "Corpo", b1 =>
                        {
                            b1.Property<Guid>("SubComentarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Conteudo")
                                .IsRequired()
                                .HasColumnType("varchar(1000)")
                                .HasColumnName("Corpo");

                            b1.HasKey("SubComentarioId");

                            b1.ToTable("SubComentarios");

                            b1.WithOwner()
                                .HasForeignKey("SubComentarioId");
                        });

                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Shared.DetalhesModificacao", "DetalhesModificacao", b1 =>
                        {
                            b1.Property<Guid>("SubComentarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DataCriacao")
                                .HasColumnType("datetime")
                                .HasColumnName("DataCriacao");

                            b1.Property<DateTime?>("DataModificacao")
                                .HasColumnType("datetime")
                                .HasColumnName("DataModificacao");

                            b1.HasKey("SubComentarioId");

                            b1.ToTable("SubComentarios");

                            b1.WithOwner()
                                .HasForeignKey("SubComentarioId");
                        });

                    b.Navigation("Corpo");

                    b.Navigation("DetalhesModificacao");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Postagens.Avaliacao", b =>
                {
                    b.HasOne("OmegaFY.Blog.Domain.Entities.Postagens.Postagem", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("PostagemId")
                        .HasConstraintName("FK_AvaliacaoPostagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Postagens.Compartilhamento", b =>
                {
                    b.HasOne("OmegaFY.Blog.Domain.Entities.Postagens.Postagem", null)
                        .WithMany("Compartilhamentos")
                        .HasForeignKey("PostagemId")
                        .HasConstraintName("FK_CompartilhamentoPostagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Postagens.Postagem", b =>
                {
                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Postagens.Cabecalho", "Cabecalho", b1 =>
                        {
                            b1.Property<Guid>("PostagemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SubTitulo")
                                .IsRequired()
                                .HasColumnType("varchar(30)")
                                .HasColumnName("SubTitulo");

                            b1.Property<string>("Titulo")
                                .IsRequired()
                                .HasColumnType("varchar(30)")
                                .HasColumnName("Titulo");

                            b1.HasKey("PostagemId");

                            b1.ToTable("Postagens");

                            b1.WithOwner()
                                .HasForeignKey("PostagemId");
                        });

                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Shared.Corpo", "Corpo", b1 =>
                        {
                            b1.Property<Guid>("PostagemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Conteudo")
                                .IsRequired()
                                .HasColumnType("varchar(8000)")
                                .HasColumnName("Corpo");

                            b1.HasKey("PostagemId");

                            b1.ToTable("Postagens");

                            b1.WithOwner()
                                .HasForeignKey("PostagemId");
                        });

                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Shared.DetalhesModificacao", "DetalhesModificacao", b1 =>
                        {
                            b1.Property<Guid>("PostagemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DataCriacao")
                                .HasColumnType("datetime")
                                .HasColumnName("DataCriacao");

                            b1.Property<DateTime?>("DataModificacao")
                                .HasColumnType("datetime")
                                .HasColumnName("DataModificacao");

                            b1.HasKey("PostagemId");

                            b1.ToTable("Postagens");

                            b1.WithOwner()
                                .HasForeignKey("PostagemId");
                        });

                    b.Navigation("Cabecalho");

                    b.Navigation("Corpo");

                    b.Navigation("DetalhesModificacao");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Comentarios.Comentario", b =>
                {
                    b.Navigation("Reacoes");

                    b.Navigation("SubComentarios");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Comentarios.SubComentario", b =>
                {
                    b.Navigation("Reacoes");
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Postagens.Postagem", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Comentarios");

                    b.Navigation("Compartilhamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
