// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmegaFY.Blog.Data.EF.Context;

#nullable disable

namespace OmegaFY.Blog.Data.EF.Migrations
{
    [DbContext(typeof(PostsContext))]
    [Migration("20220411120242_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Posts.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("OmegaFY.Blog.Domain.Entities.Posts.Post", b =>
                {
                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Posts.Author", "Author", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("varchar(36)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("varchar(36)")
                                .HasColumnName("AuthorId");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Posts.Body", "Body", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("varchar(36)");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Content");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Posts.Header", "Header", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("varchar(36)");

                            b1.Property<string>("SubTitle")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("SubTitle");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Title");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsOne("OmegaFY.Blog.Domain.ValueObjects.Shared.ModificationDetails", "ModificationDetails", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("varchar(36)");

                            b1.Property<DateTime>("DateOfCreation")
                                .HasColumnType("datetime")
                                .HasColumnName("DateOfCreation");

                            b1.Property<DateTime?>("DateOfModification")
                                .IsRequired()
                                .HasColumnType("datetime")
                                .HasColumnName("DateOfModification");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("Author");

                    b.Navigation("Body");

                    b.Navigation("Header");

                    b.Navigation("ModificationDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
