// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmegaFY.Blog.Data.EF.Context;

#nullable disable

namespace OmegaFY.Blog.Data.EF.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.AvaliationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<Guid>("PostId")
                        .HasColumnType("varchar(36)");

                    b.Property<byte>("Rate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Avaliations", (string)null);
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.CommentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<Guid>("PostId")
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.PostModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("varchar(36)");

                    b.Property<int>("AverageRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfModification")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SubTitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.ReactionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CommentReaction")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("Reactions", (string)null);
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.SharedModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("DateAndTimeOfShare")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PostId")
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Shares", (string)null);
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.AvaliationModel", b =>
                {
                    b.HasOne("OmegaFY.Blog.Data.EF.Models.PostModel", null)
                        .WithMany("Avaliations")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.CommentModel", b =>
                {
                    b.HasOne("OmegaFY.Blog.Data.EF.Models.PostModel", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.ReactionModel", b =>
                {
                    b.HasOne("OmegaFY.Blog.Data.EF.Models.CommentModel", null)
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.SharedModel", b =>
                {
                    b.HasOne("OmegaFY.Blog.Data.EF.Models.PostModel", null)
                        .WithMany("Shareds")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.CommentModel", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("OmegaFY.Blog.Data.EF.Models.PostModel", b =>
                {
                    b.Navigation("Avaliations");

                    b.Navigation("Comments");

                    b.Navigation("Shareds");
                });
#pragma warning restore 612, 618
        }
    }
}
